version: "3"

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    ports:
      - 3000:3000
    depends_on:
      - database

  redis:
    image: redis

  sidekiq:
    command: bundle exec sidekiq
    build: .
    depends_on:
      - redis

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: docker_project_development
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db_date:/var/lib/mysql

volumes:
  db_date:
  gem_cache:





